# Generated by Django 5.1.3 on 2024-12-28 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0003_contest_name_en_contest_name_kk_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название контеста ru'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name_en',
            field=models.CharField(max_length=128, verbose_name='Название контеста en'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name_kk',
            field=models.CharField(max_length=128, verbose_name='Название контеста kk'),
        ),
        migrations.AlterField(
            model_name='usercontest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contests', to=settings.AUTH_USER_MODEL, verbose_name='ID пользователя'),
        ),
    ]
