# Generated by Django 5.1.3 on 2024-12-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0004_alter_contest_name_alter_contest_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на контест'),
        ),
    ]
