# Generated by Django 5.1.3 on 2025-01-11 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0005_contest_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField(verbose_name='Ранг')),
                ('points', models.FloatField(default=0, verbose_name='Очки')),
                ('user_reg', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='contest.usercontest', verbose_name='Регистрация')),
            ],
        ),
    ]
