# Generated by Django 5.1.3 on 2025-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0007_contest_show_on_main_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
