# Generated by Django 5.1.3 on 2025-01-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0008_contest_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='registration_open',
            field=models.BooleanField(default=True),
        ),
    ]
