# Generated by Django 5.1.3 on 2025-01-22 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0009_contest_registration_open'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='fields',
        ),
    ]
