# Generated by Django 5.1.3 on 2025-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_remove_contest_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='required_fields',
        ),
        migrations.AddField(
            model_name='contest',
            name='fields',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
