# Generated by Django 5.1.3 on 2025-01-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0011_remove_contest_required_fields_contest_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercontest',
            options={'ordering': ['id'], 'verbose_name': 'Данные пользователей к контестам', 'verbose_name_plural': 'Данные пользователей к контестам'},
        ),
        migrations.AddField(
            model_name='contest',
            name='image_url',
            field=models.CharField(default='capybara.png'),
        ),
        migrations.AddField(
            model_name='contest',
            name='level_on_main_page',
            field=models.IntegerField(default=1),
        ),
    ]
