# Generated by Django 5.1.3 on 2025-01-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0013_alter_usercontest_additional_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='trial_contest_link',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Ссылка на пробный тур'),
        ),
    ]
