# Generated by Django 5.1.3 on 2025-02-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0014_contest_trial_contest_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='text_above_submit_button',
            field=models.TextField(blank=True, null=True),
        ),
    ]
