# Generated by Django 5.1.3 on 2025-02-03 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0015_contest_text_above_submit_button'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='text_above_submit_button_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_above_submit_button_kk',
            field=models.TextField(blank=True, null=True),
        ),
    ]
