# Generated by Django 5.1.3 on 2025-02-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0016_contest_text_above_submit_button_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Название контеста'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название контеста'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name_en',
            field=models.CharField(max_length=128, null=True, verbose_name='Название контеста'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Название контеста'),
        ),
    ]
