# Generated by Django 5.1.3 on 2025-02-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0017_contest_name_ru_alter_contest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='playing_desc_ru',
            field=models.TextField(null=True, verbose_name='Описание контеста: '),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_above_submit_button_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contest',
            name='playing_desc',
            field=models.TextField(verbose_name='Описание контеста: '),
        ),
        migrations.AlterField(
            model_name='contest',
            name='playing_desc_en',
            field=models.TextField(null=True, verbose_name='Описание контеста: '),
        ),
        migrations.AlterField(
            model_name='contest',
            name='playing_desc_kk',
            field=models.TextField(null=True, verbose_name='Описание контеста: '),
        ),
    ]
