# Generated by Django 5.1.3 on 2025-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0018_contest_playing_desc_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='text_after_submit',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_after_submit_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_after_submit_kk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contest',
            name='text_after_submit_ru',
            field=models.TextField(blank=True, null=True),
        ),
    ]
