# Generated by Django 5.1.3 on 2025-02-04 20:42

import contest.utils.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0020_contest_is_contest_alter_contest_playing_desc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontest',
            name='additional_fields',
            field=models.JSONField(default=dict, encoder=contest.utils.json_encoder.CustomJSONEncoder),
        ),
    ]
