# Generated by Django 5.1.3 on 2025-02-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0021_alter_usercontest_additional_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='image_url',
            field=models.CharField(default='https://i.ibb.co.com/7tSBNdmf/capybara.png'),
        ),
    ]
