# Generated by Django 5.1.3 on 2025-02-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0022_alter_contest_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='esep_org',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID огранизации в esep'),
        ),
    ]
