# Generated by Django 5.1.3 on 2025-02-10 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0023_contest_esep_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='tmp_cpfed_token',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
