# Generated by Django 5.1.3 on 2025-03-16 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0025_contest_text_instead_of_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contest',
            name='is_contest',
        ),
        migrations.RemoveField(
            model_name='contest',
            name='tmp_cpfed_token',
        ),
    ]
