# Generated by Django 5.1.3 on 2025-03-18 20:32

import contest.utils.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0026_remove_contest_is_contest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontest',
            name='additional_fields',
            field=models.JSONField(blank=True, default=dict, encoder=contest.utils.json_encoder.CustomJSONEncoder),
        ),
    ]
