# Generated by Django 5.1.3 on 2025-03-26 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0027_alter_usercontest_additional_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('fields', models.JSONField(blank=True, null=True)),
                ('full_data', models.JSONField(blank=True, null=True)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contest.contest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
