# Generated by Django 5.1.3 on 2025-03-30 10:13

import contest.utils.json_encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0028_contestchangelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestchangelog',
            name='full_data',
            field=models.JSONField(blank=True, encoder=contest.utils.json_encoder.CustomJSONEncoder, null=True),
        ),
    ]
