# Generated by Django 5.1.3 on 2025-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0029_alter_contestchangelog_full_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='telegram_notifications_scheduled',
            field=models.BooleanField(default=False),
        ),
    ]
