apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: '
server {
    listen       80;
    listen       [::]:80;
    server_name  _;
    client_max_body_size 48M;

    add_header X-UA-Compatible "IE=Edge,chrome=1";
    add_header X-Content-Type-Options nosniff;
    add_header X-XSS-Protection "1; mode=block";
    add_header Content-Security-Policy "frame-ancestors app.oqylyq.kz";
    add_header Cross-Origin-Opener-Policy same-origin-allow-popups;
    
    # CORS headers for oauth.telegram.org
    add_header Access-Control-Allow-Origin "https://oauth.telegram.org";
    add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
    add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";
    add_header Access-Control-Allow-Credentials "true";
    
    # For preflight OPTIONS requests
    if ($request_method = "OPTIONS") {
        add_header Access-Control-Allow-Origin "https://oauth.telegram.org";
        add_header Access-Control-Allow-Methods "GET, POST, OPTIONS";
        add_header Access-Control-Allow-Headers "DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization";
        add_header Access-Control-Allow-Credentials "true";
        add_header Access-Control-Max-Age "1728000";
        add_header Content-Type "text/plain charset=UTF-8";
        add_header Content-Length "0";
        return 204;
    }

    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header Server nginx/$nginx_version;
    proxy_read_timeout 30;

    location / {
        proxy_pass http://127.0.0.1:8000;
    }
}
'
