apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-cpfed
  labels:
    app: auth-cpfed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-cpfed
  template:
    metadata:
      labels:
        app: auth-cpfed
        app.kubernetes.io/name: auth-cpfed
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
              name: auth-nginx-svc
          volumeMounts:
            - name: config-vol
              mountPath: "/etc/nginx/conf.d/"
        - name: auth-cpfed 
          image: zharaskhan/auth-cpfed-master
          imagePullPolicy: "Always"
          workingDir: /app/
          command: ["sh", "-c"]
          args:
          - |
            echo "$(pwd)"
            echo "Hello from auth-cpfed"
            ./docker/web_entrypoint.sh
          ports:
            - containerPort: 8000
              name: auth-svc
          resources: {}
          envFrom:
            - configMapRef:
                name: auth-configmap
          env:
            - name: REDIS_HOST
              value: $(AUTH_REDIS_SERVICE_HOST)
      restartPolicy: Always
      volumes:
      - name: config-vol
        configMap:
          name: nginx-config
          items:
            - key: nginx.conf
              path: nginx.conf
---
apiVersion: v1
kind: Pod
metadata:
  name: auth-redis
  labels:
    app.kubernetes.io/name: auth-redis
spec:
  containers:
  - name: auth-redis
    image: "docker.io/redis:6.0.5"
    ports:
      - containerPort: 6379
        name: auth-redis-svc
