apiVersion: v1
kind: Service
metadata:
  name: auth-cpfed
spec:
  selector:
    app.kubernetes.io/name: auth-cpfed
  ports:
  - name: http
    protocol: TCP
    port: 31746
    targetPort: auth-nginx-svc
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: auth-redis
spec:
  selector:
    app.kubernetes.io/name: auth-redis
  ports:
  - port: 6379
    targetPort: auth-redis-svc
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: auth-nginx-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/use-forwarded-headers: "true"
    nginx.ingress.kubernetes.io/real-ip-header: "X-Forwarded-For"
    nginx.ingress.kubernetes.io/x-forwarded-for-header: "X-Forwarded-For"
spec:
  externalTrafficPolicy: Local
  ingressClassName: nginx
  tls:
  - hosts:
    - auth.cpfed.kz
    secretName: auth-tls-secret
  rules:
  - host: auth.cpfed.kz
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: auth-cpfed
              port:
                number: 31746