apiVersion: v1
kind: Service
metadata:
  name: auth-cpfed
spec:
  selector:
    app.kubernetes.io/name: auth-cpfed
  ports:
  - name: http
    protocol: TCP
    port: 31746
    targetPort: auth-svc
  type: LoadBalancer
