# Generated by Django 5.1.3 on 2024-11-30 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useractivation',
            name='password',
            field=models.CharField(default='a', max_length=128, verbose_name='Пароль'),
            preserve_default=False,
        ),
    ]
