# Generated by Django 5.1.3 on 2024-12-01 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_useractivation_password'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locations.region', verbose_name='Регион'),
        ),
    ]
