# Generated by Django 5.1.3 on 2024-12-02 17:59

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_mainuser_handle_alter_useractivation_handle'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordrecovery',
            options={'ordering': ['-expiration_date'], 'verbose_name': 'Восстановление пароля', 'verbose_name_plural': 'Восстановление пароля'},
        ),
        migrations.AlterModelOptions(
            name='useractivation',
            options={'ordering': ['-expiration_date'], 'verbose_name': 'Активация аккаунта', 'verbose_name_plural': 'Активация аккаунта'},
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('MAN', 'Мужской'), ('WOMAN', 'Женский'), ('NON_BINARY', 'Небинарный')], max_length=20, null=True, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='passwordrecovery',
            name='expiration_date',
            field=models.DateTimeField(default=authentication.models._password_default_exp_date, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='expiration_date',
            field=models.DateTimeField(default=authentication.models._password_default_exp_date, verbose_name='Срок годности'),
        ),
    ]
