# Generated by Django 5.1.3 on 2024-12-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_passwordrecovery_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='uin',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='ИИН'),
        ),
    ]
