# Generated by Django 5.1.3 on 2024-12-03 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_alter_mainuser_phone_number_alter_mainuser_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='uin',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='ИИН'),
        ),
    ]
