# Generated by Django 5.1.3 on 2024-12-03 12:45

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_alter_mainuser_phone_number_alter_mainuser_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, null=True, region=None, unique=True, verbose_name='Телефонный номер'),
        ),
    ]
