# Generated by Django 5.1.3 on 2024-12-28 04:28

import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_mainuser_uin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='handle',
            field=models.CharField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Хэндл может состоять только из латинских букв, цифр и _', regex=re.compile('^[a-z_0-9]+$'))], verbose_name='Хэндл'),
        ),
        migrations.AlterField(
            model_name='useractivation',
            name='handle',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Хэндл может состоять только из латинских букв, цифр и _', regex=re.compile('^[a-z_0-9]+$'))], verbose_name='Хэндл'),
        ),
    ]
