# Generated by Django 5.1.3 on 2025-03-14 11:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_mainuser_handle_alter_useractivation_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='mainuser',
            name='telegram_token',
            field=models.CharField(default=uuid.uuid4, max_length=128, verbose_name='Telegram TOKEN'),
        ),
        migrations.AlterField(
            model_name='mainuser',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True, verbose_name='Размер футболки'),
        ),
    ]
