# Generated by Django 5.1.3 on 2025-03-16 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_mainuser_handle_alter_useractivation_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainuser',
            name='t_shirt_size',
            field=models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True, verbose_name='Размер футболки'),
        ),
    ]
