# Generated by Django 5.1.3 on 2025-03-18 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_mainuser_t_shirt_size'),
        ('contest', '0026_remove_contest_is_contest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnsiteLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expiration_date', models.DateTimeField(verbose_name='Срок годности')),
                ('secret_code', models.CharField(unique=True, verbose_name='Секретный код')),
                ('contest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contest.contest', verbose_name='Контест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OnsiteLoginLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=100, verbose_name='IP адрес')),
                ('created_time', models.DateTimeField(verbose_name='Время использования')),
                ('onsite_login', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log', to='authentication.onsitelogin', verbose_name='Использованный код')),
            ],
        ),
    ]
