# Generated by Django 5.1.3 on 2025-03-18 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_onsitelogin_onsiteloginlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainuser',
            name='is_offline',
            field=models.BooleanField(default=False, verbose_name='Участвует в онлайн соревновании?'),
        ),
        migrations.AlterField(
            model_name='onsiteloginlogs',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Время использования'),
        ),
    ]
