# Generated by Django 5.1.3 on 2025-03-30 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_mainuser_telegram_id_mainuser_telegram_token_and_more'),
        ('authentication', '0015_remove_mainuser_is_offline_alter_onsitelogin_user'),
    ]

    operations = [
    ]
