# Generated by Django 5.1.3 on 2025-03-30 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_merge_20250330_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='telegram_token',
        ),
    ]
