# Generated by Django 5.1.3 on 2025-04-08 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0017_remove_mainuser_telegram_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainuser',
            name='telegram_id',
        ),
    ]
