# Generated by Django 5.1.3 on 2025-04-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_onsiteloginlogs_onsite_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='onsitelogin',
            name='is_one_time',
            field=models.BooleanField(default=False, verbose_name='Одноразовый ли код?'),
        ),
    ]
