# Generated by Django 5.1.3 on 2025-04-26 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0020_onsitelogin_is_one_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onsiteloginlogs',
            name='onsite_login',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='authentication.onsitelogin', verbose_name='Использованный код'),
        ),
    ]
