# Generated by Django 5.1.3 on 2025-04-08 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('chat_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Telegram ID')),
                ('language', models.CharField(choices=[('kk', 'Қазақша'), ('en', 'English'), ('ru', 'Русский язык')], default=0, max_length=2)),
                ('user_group', models.PositiveSmallIntegerField(choices=[(0, 'Школьник'), (1, 'Студент'), (2, 'Учитель'), (3, 'Работник компании')], default=0)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram', to=settings.AUTH_USER_MODEL, verbose_name='Телеграм')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('chat_id',), name='unique_chat_id')],
            },
        ),
    ]
