# Generated by Django 5.1.3 on 2025-04-14 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0029_alter_contestchangelog_full_data'),
        ('telegram_bot', '0002_telegramuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('scheduled', models.BooleanField(default=False)),
                ('day_before_sent', models.BooleanField(default=False)),
                ('hour_before_sent', models.BooleanField(default=False)),
                ('day_before_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('hour_before_task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('contest', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='telegram_notification', to='contest.contest')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
