# Generated by Django 5.1.3 on 2025-05-26 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0003_contestnotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramQA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего изменения')),
                ('status', models.SmallIntegerField(choices=[(0, 'Получено'), (1, 'В обработке'), (2, 'Обработано')], default=0, verbose_name='Статус вопроса.')),
                ('text', models.TextField(blank=True, null=True, verbose_name='Текст вопроса: ')),
                ('request_write_mode', models.BooleanField(default=False)),
                ('telegram_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='telegram_bot.telegramuser', verbose_name='Телеграм')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
